# Generated by Django 3.1 on 2022-08-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220817_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_price',
            field=models.IntegerField(default=0),
        ),
    ]
